# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef63/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/pantech/ef63/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/pantech/ef63/proprietary/lib/hw/camera.msm8974.so:system/lib/hw/camera.msm8974.so \
    vendor/pantech/ef63/proprietary/lib/libsnsutils.so:system/lib/libsnsutils.so
